#!/bin/sh

#Created by "Gautham Santhosh"
clear

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'#No Color


# check if upstream remote exists
git ls-remote --exit-code upstream &> /dev/null
if [[ $? -ne 0 ]]; then
    printf "${RED}No remote 'upstream'.\n${NC}Remotes:\n"
    git remote
    exit 0
fi

git fetch upstream master
git merge upstream/master
git push origin master

if [ $# -eq 0 ]
    then
        read -p "Enter branch name : " branch
fi
git checkout -b $branch
