#!/bin/sh

#Created by "Gautham Santhosh"
clear

# check if upstream remote exists
git ls-remote --exit-code upstream &> /dev/null
if [[ $? -ne 0 ]]; then
    printf "No remote 'upstream'.\n$Remotes:\n"
    git remote
    read -p "Enter remote url : " upstream
    add_upstream="git remote add upstream $upstream"
    eval $add_upstream
fi

git fetch upstream master
git merge upstream/master
git push origin master

if [ $# -eq 0 ]
    then
        read -p "Enter branch name : " branch
else
    branch=$1
fi


git checkout -b $branch
